apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes-config
  namespace: hermes
data:
  config.yaml.tpl: |
    model:
      provider: "custom"
      base_url: "@LITELLM_BASE_URL@"
      default: "@LITELLM_MODEL@"
      api_key: "@LITELLM_API_KEY@"

    auxiliary:
      vision:
        base_url: "@LITELLM_BASE_URL@"
        api_key: "@LITELLM_API_KEY@"
        model: "smart-fast"
      web_extract:
        base_url: "@LITELLM_BASE_URL@"
        api_key: "@LITELLM_API_KEY@"
        model: "smart-fast"
      compression:
        base_url: "@LITELLM_BASE_URL@"
        api_key: "@LITELLM_API_KEY@"
        model: "smart-fast"
      session_search:
        base_url: "@LITELLM_BASE_URL@"
        api_key: "@LITELLM_API_KEY@"
        model: "smart-fast"
      skills_hub:
        base_url: "@LITELLM_BASE_URL@"
        api_key: "@LITELLM_API_KEY@"
        model: "smart-fast"
      approval:
        base_url: "@LITELLM_BASE_URL@"
        api_key: "@LITELLM_API_KEY@"
        model: "smart-fast"
      mcp:
        base_url: "@LITELLM_BASE_URL@"
        api_key: "@LITELLM_API_KEY@"
        model: "smart-fast"
      title_generation:
        base_url: "@LITELLM_BASE_URL@"
        api_key: "@LITELLM_API_KEY@"
        model: "smart-fast"
      triage_specifier:
        base_url: "@LITELLM_BASE_URL@"
        api_key: "@LITELLM_API_KEY@"
        model: "smart-fast"
      curator:
        base_url: "@LITELLM_BASE_URL@"
        api_key: "@LITELLM_API_KEY@"
        model: "smart-fast"
